import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import ReduxProvider from "./components/ReduxProvider";
import { Toaster } from "@/components/ui/sonner";
import AuthIntializer from "./components/AuthIntializer";
import ProductsInitializer from "./components/ProductsInitializer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <AuthIntializer>
            {/* <ProductsInitializer> */}
            <Toaster position="top-center" />
            <Header />
            <div className="main min-h-screen  max-w-7xl mx-auto">
              {children}
            </div>
            {/* </ProductsInitializer> */}
          </AuthIntializer>
        </ReduxProvider>
        <Footer />
      </body>
    </html>
  );
}
